CREATE TABLE TBMECANICO (
   MECANICO_CODIGO        NUMERIC(5) PRIMARY KEY NOT NULL,	
   MECANICO_NOME          VARCHAR(100)		     NOT NULL,
   MECANICO_ENDEREÇO      VARCHAR(255)		     NOT NULL,
   MECANICO_ESPECIALIDADE VARCHAR(20)		     NOT NULL
)

CREATE TABLE TBEQUIPE (
  EQUIPE_CODIGO	NUMERIC(5)	 PRIMARY KEY NOT NULL,
  EQUIPE_AREA  	VARCHAR(100)		     NOT NULL
)

CREATE TABLE TBCLIENTE (
	  CLIENTE_CODIGO  	NUMERIC(5)	PRIMARY KEY	NOT NULL,
	  CLIENTE_NOME    	VARCHAR(100)		    NOT NULL,
	  CLIENTE_ENDEREÇO	VARCHAR(255)		    NOT NULL,
	  CLIENTE_TELEFONE	VARCHAR(20)		        NOT NULL
)
CREATE TABLE TBVEICULO (     				
	  VEICULO_CODIGO    	NUMERIC(5)	PRIMARY KEY	NOT NULL,
	  VEICULO_PLACA     	VARCHAR(15)		        NOT NULL,
      VEICULO_DESCRICAO 	VARCHAR(100)		    NOT NULL
)

CREATE TABLE TBSERVICO (
	  SERVICO_CODIGO     NUMERIC(5)	PRIMARY KEY	NOT NULL,
	  SERVICO_PRECOTOTAL NUMERIC(10,2)		    NOT NULL,
	  SERVICO_PRECMDO    NUMERIC(10,2)		    NOT NULL
)

CREATE TABLE TBOS(                				
	  OS_CODIGO           	NUMERIC(5)	PRIMARY KEY	 NOT NULL,
	  OS_DTDEEMISSÃO    	NUMERIC(8)		         NOT NULL,
	  OS_VALOR            	NUMERIC(10,2)	         NOT NULL,
	  OS_DTDECONCLUSÃO  	NUMERIC(8)		         NOT NULL,
	  OS_COD_EQUIPE       	NUMERIC(5) CONSTRAINT TBOSEQUIPE FOREIGN KEY REFERENCES TBEQUIPE(EQUIPE_CODIGO)	NOT NULL
)

CREATE TABLE TBPECAS(
  PECAS_CODIGO   	NUMERIC(5)	PRIMARY KEY	NOT NULL,
  PECAS_PREÇO    	NUMERIC(10,2)		    NOT NULL

)
CREATE TABLE TBOSXSERVICO(
  SXOS_CODIGO        	NUMERIC(5)	PRIMARY KEY	NOT NULL,
  SXOS_COD_OS        	NUMERIC(5)	CONSTRAINT TBOSXSERVICOOS FOREIGN KEY REFERENCES TBOS(OS_CODIGO)	NOT NULL,
  SXOS_CODIGO_SERVICO	NUMERIC(5)	CONSTRAINT TBOSXSERVICOSER FOREIGN KEY REFERENCES TBSERVICO(SERVICO_CODIGO)	NOT NULL
) 
CREATE TABLE PECASXSERVICOS(
  PXS_CODIGO	     NUMERIC(5)	PRIMARY KEY	NOT NULL,
  PXS_CODIGO_SERVICO NUMERIC(5)	CONSTRAINT TBPCXSERSER FOREIGN KEY REFERENCES TBSERVICO(SERVICO_CODIGO)	NOT NULL,
  PXS_CODIGO_PECA	 NUMERIC(5)	CONSTRAINT TBPCXSERPC FOREIGN KEY REFERENCES TBPECAS(PECAS_CODIGO)	    NOT NULL
)
	
CREATE TABLE MECANICOXEQUIPE(
  CODIGO         	NUMERIC(5)	PRIMARY KEY	NOT NULL,
  CODIGO_MECANICO	NUMERIC(5)	CONSTRAINT MXEQUIPMEC FOREIGN KEY REFERENCES TBMECANICO(MECANICO_CODIGO) NOT NULL,
  CODIGO_EQUIPE  	NUMERIC(5)	CONSTRAINT MXEQUIPEQUI FOREIGN KEY REFERENCES TBEQUIPE(EQUIPE_CODIGO)	 NOT NULL
)

CREATE TABLE CLIENTEXVEICULO(
   CXVEI_COGIGO	        NUMERIC(5)	PRIMARY KEY	NOT NULL,
   CXVEI_COGIDO_CLIENTE	NUMERIC(5)	CONSTRAINT CLIXVEICLIE FOREIGN KEY REFERENCES TBCLIENTE(CLIENTE_CODIGO)	NOT NULL,
   CXVEI_CODIGO_VEICULO	NUMERIC(5)	CONSTRAINT CLIXVEIVEIC FOREIGN KEY REFERENCES TBVEICULO(VEICULO_CODIGO)	NOT NULL

)

CREATE TABLE OSXEQUIPE( 
  EXOSCODIGO     NUMERIC(5)	PRIMARY KEY	NOT NULL,
  EXOSCODIGO_OS  NUMERIC(5)	CONSTRAINT OSXQUIEPEOS FOREIGN KEY REFERENCES TBOS(OS_CODIGO)	NOT NULL,
  EXOSCODIGCO_EQUIPE NUMERIC(5)	CONSTRAINT OSXQUIEPEEQ FOREIGN KEY REFERENCES TBEQUIPE(EQUIPE_CODIGO)	NOT NULL
 
 )
 CREATE TABLE VEICULOXOS(
  VXOSCODIGO  NUMERIC(5)	PRIMARY KEY	NOT NULL,
  VXOSCODIGO_OS NUMERIC(5)	CONSTRAINT VEICXOS FOREIGN KEY REFERENCES TBOS(OS_CODIGO)	NOT NULL,
  VXOSCODIGO_VEICULO NUMERIC(5)	CONSTRAINT OSXQUIEPEOS FOREIGN KEY REFERENCES TBVEICULO(VEICULO_CODIGO)	NOT NULL

  )
  